[0m01:23:45.420900 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D97E7990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D8D58BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D9B2C190>]}


============================== 01:23:45.433914 | fc7418c8-35b5-42b3-9923-2d0e99a2af56 ==============================
[0m01:23:45.433914 [info ] [MainThread]: Running with dbt=1.9.1
[0m01:23:45.433914 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:23:45.433914 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:23:45.433914 [debug] [MainThread]: Command `dbt run` failed at 01:23:45.433914 after 0.10 seconds
[0m01:23:45.433914 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D9B01C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D32A4D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D9B2C390>]}
[0m01:23:45.433914 [debug] [MainThread]: Flushing usage events
[0m01:23:45.962992 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:04:37.765692 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000297889600D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000297889A0950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029788961CD0>]}


============================== 11:04:37.770978 | df6994d5-cd0b-4938-af38-530541856bbd ==============================
[0m11:04:37.770978 [info ] [MainThread]: Running with dbt=1.9.1
[0m11:04:37.774065 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:04:37.775065 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:04:37.778085 [debug] [MainThread]: Command `dbt run` failed at 11:04:37.778085 after 0.14 seconds
[0m11:04:37.780075 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000297889F0610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000297889F0910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000297889F1AD0>]}
[0m11:04:37.781105 [debug] [MainThread]: Flushing usage events
[0m11:04:38.317817 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:39:40.381541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215AF8B6D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215AF900090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215AF8B6410>]}


============================== 10:39:40.381541 | ecda825a-3333-4dc2-a746-24d80512b3b9 ==============================
[0m10:39:40.381541 [info ] [MainThread]: Running with dbt=1.8.6
[0m10:39:40.381541 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m10:39:40.381541 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:39:40.381541 [debug] [MainThread]: Command `dbt run` failed at 10:39:40.381541 after 0.14 seconds
[0m10:39:40.381541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215AF8BCB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215A90F2810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215AF91C490>]}
[0m10:39:40.381541 [debug] [MainThread]: Flushing usage events
[0m10:40:46.649447 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A766A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A7AF610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A7AE790>]}


============================== 10:40:46.664095 | 64a64e40-7f08-4380-8eb0-e3d64d403a50 ==============================
[0m10:40:46.664095 [info ] [MainThread]: Running with dbt=1.8.6
[0m10:40:46.664095 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m10:40:46.715198 [info ] [MainThread]: dbt version: 1.8.6
[0m10:40:46.716579 [info ] [MainThread]: python version: 3.11.5
[0m10:40:46.716579 [info ] [MainThread]: python path: C:\Users\lina_\AppData\Local\Programs\Python\Python311\python.exe
[0m10:40:46.716579 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m10:41:01.875667 [info ] [MainThread]: Using profiles dir at C:\Users\lina_\.dbt
[0m10:41:01.875667 [info ] [MainThread]: Using profiles.yml file at C:\Users\lina_\.dbt\profiles.yml
[0m10:41:01.877887 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
[0m10:41:01.879219 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m10:41:01.881029 [debug] [MainThread]: Command `dbt debug` failed at 10:41:01.881029 after 15.32 seconds
[0m10:41:01.881029 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A7D2950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A76CA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A527B10>]}
[0m10:41:01.881029 [debug] [MainThread]: Flushing usage events
[0m10:45:43.568306 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F8026D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F7CF5190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F7CF5110>]}


============================== 10:45:43.569340 | 9a29aa34-ac46-48c5-89e2-930927ef6c85 ==============================
[0m10:45:43.569340 [info ] [MainThread]: Running with dbt=1.8.6
[0m10:45:43.573389 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt clean', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:45:43.573389 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:45:43.573389 [debug] [MainThread]: Command `dbt clean` failed at 10:45:43.573389 after 0.12 seconds
[0m10:45:43.573389 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F802CD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F8086850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F8087790>]}
[0m10:45:43.578405 [debug] [MainThread]: Flushing usage events
[0m22:36:50.509715 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A163B036D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A1638F9910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A163B46250>]}


============================== 22:36:50.671538 | 4ac5e67d-69bb-4d3f-83e7-f3871a746718 ==============================
[0m22:36:50.671538 [info ] [MainThread]: Running with dbt=1.9.1
[0m22:36:50.673793 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:36:50.675800 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:36:50.677789 [debug] [MainThread]: Command `dbt run` failed at 22:36:50.677789 after 0.38 seconds
[0m22:36:50.679790 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A1638FA350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A1638F1410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A15C242090>]}
[0m22:36:50.680790 [debug] [MainThread]: Flushing usage events
[0m22:36:51.135779 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:37:16.176725 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F0B4ECAD50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F0B0F42D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F0B4EFD350>]}


============================== 22:37:16.193942 | 17dabed6-c349-4d39-834c-8f1b3ceec013 ==============================
[0m22:37:16.193942 [info ] [MainThread]: Running with dbt=1.9.1
[0m22:37:16.193942 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m22:37:16.647683 [info ] [MainThread]: dbt version: 1.9.1
[0m22:37:16.647683 [info ] [MainThread]: python version: 3.11.5
[0m22:37:16.647683 [info ] [MainThread]: python path: C:\Users\lina_\Desktop\wh_examarb\.venv\Scripts\python.exe
[0m22:37:16.647683 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m22:37:20.878943 [info ] [MainThread]: Using profiles dir at C:\Users\lina_\.dbt
[0m22:37:20.878943 [info ] [MainThread]: Using profiles.yml file at C:\Users\lina_\.dbt\profiles.yml
[0m22:37:20.878943 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
[0m22:37:20.878943 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m22:37:20.878943 [debug] [MainThread]: Command `dbt debug` failed at 22:37:20.878943 after 4.79 seconds
[0m22:37:20.878943 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F0AE754A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F0B4F53DD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F0B4F53E90>]}
[0m22:37:20.878943 [debug] [MainThread]: Flushing usage events
[0m22:37:21.306960 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:52:11.623657 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D9847A3B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D984797790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D983A62E50>]}


============================== 23:52:11.623657 | 638d2100-c96b-4689-9f48-009c676e9f29 ==============================
[0m23:52:11.623657 [info ] [MainThread]: Running with dbt=1.9.1
[0m23:52:11.623657 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbt_code', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:52:11.648637 [debug] [MainThread]: Starter project path: C:\Users\lina_\Desktop\wh_examarb\.venv\Lib\site-packages\dbt\include\starter_project
[0m23:52:11.677569 [info ] [MainThread]: 
Your new dbt project "dbt_code" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:52:11.678612 [info ] [MainThread]: Setting up your profile.
[0m23:54:16.652828 [info ] [MainThread]: Profile dbt_code written to C:\Users\lina_\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m23:54:16.658053 [debug] [MainThread]: Command `dbt init` succeeded at 23:54:16.657001 after 125.09 seconds
[0m23:54:16.659606 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D9FDF84DD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D984632050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D98472F5D0>]}
[0m23:54:16.660598 [debug] [MainThread]: Flushing usage events
[0m23:54:17.110433 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:55:18.230562 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002989DB5F690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002989DB69790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002989DB9D350>]}


============================== 23:55:18.233055 | 7952a7b7-701f-4137-ac23-88c7b893ad8c ==============================
[0m23:55:18.233055 [info ] [MainThread]: Running with dbt=1.9.1
[0m23:55:18.233055 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dbt_code', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:55:18.262855 [info ] [MainThread]: A project called dbt_code already exists here.
[0m23:55:18.265255 [debug] [MainThread]: Command `dbt init` succeeded at 23:55:18.265255 after 0.13 seconds
[0m23:55:18.266267 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002989DB69790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029897414D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029897414D10>]}
[0m23:55:18.267293 [debug] [MainThread]: Flushing usage events
[0m23:55:18.787119 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:55:54.633357 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CAA746450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CAA747F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CAA744610>]}


============================== 23:55:54.637883 | 3b1db353-a803-4aea-854a-67c93d964257 ==============================
[0m23:55:54.637883 [info ] [MainThread]: Running with dbt=1.9.1
[0m23:55:54.638841 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m23:55:54.660717 [info ] [MainThread]: dbt version: 1.9.1
[0m23:55:54.661221 [info ] [MainThread]: python version: 3.11.5
[0m23:55:54.662862 [info ] [MainThread]: python path: C:\Users\lina_\Desktop\wh_examarb\.venv\Scripts\python.exe
[0m23:55:54.663899 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m23:55:55.545082 [info ] [MainThread]: Using profiles dir at C:\Users\lina_\.dbt
[0m23:55:55.545082 [info ] [MainThread]: Using profiles.yml file at C:\Users\lina_\.dbt\profiles.yml
[0m23:55:55.545082 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
[0m23:55:55.569343 [info ] [MainThread]: adapter type: snowflake
[0m23:55:55.572003 [info ] [MainThread]: adapter version: 1.9.0
[0m23:55:55.572003 [info ] [MainThread]: Configuration:
[0m23:55:55.573839 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m23:55:55.573839 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m23:55:55.576185 [info ] [MainThread]: Required dependencies:
[0m23:55:55.576185 [debug] [MainThread]: Executing "git --help"
[0m23:55:55.598496 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m23:55:55.598496 [debug] [MainThread]: STDERR: "b''"
[0m23:55:55.598496 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m23:55:55.613903 [info ] [MainThread]: Connection:
[0m23:55:55.615507 [info ] [MainThread]:   account: ew35625.west-europe.azure
[0m23:55:55.615507 [info ] [MainThread]:   user: dbt_transformer
[0m23:55:55.619376 [info ] [MainThread]:   database: wh_db
[0m23:55:55.620189 [info ] [MainThread]:   warehouse: compute_wh
[0m23:55:55.621209 [info ] [MainThread]:   role: dbt_role
[0m23:55:55.622257 [info ] [MainThread]:   schema: warehouse
[0m23:55:55.622868 [info ] [MainThread]:   authenticator: None
[0m23:55:55.623985 [info ] [MainThread]:   oauth_client_id: None
[0m23:55:55.624992 [info ] [MainThread]:   query_tag: None
[0m23:55:55.626162 [info ] [MainThread]:   client_session_keep_alive: False
[0m23:55:55.626162 [info ] [MainThread]:   host: None
[0m23:55:55.627171 [info ] [MainThread]:   port: None
[0m23:55:55.628272 [info ] [MainThread]:   proxy_host: None
[0m23:55:55.629284 [info ] [MainThread]:   proxy_port: None
[0m23:55:55.631285 [info ] [MainThread]:   protocol: None
[0m23:55:55.631996 [info ] [MainThread]:   connect_retries: 1
[0m23:55:55.631996 [info ] [MainThread]:   connect_timeout: None
[0m23:55:55.635712 [info ] [MainThread]:   retry_on_database_errors: False
[0m23:55:55.637409 [info ] [MainThread]:   retry_all: False
[0m23:55:55.639549 [info ] [MainThread]:   insecure_mode: False
[0m23:55:55.640568 [info ] [MainThread]:   reuse_connections: True
[0m23:55:55.641695 [info ] [MainThread]: Registered adapter: snowflake=1.9.0
[0m23:55:56.065570 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m23:56:00.889630 [debug] [MainThread]: Using snowflake connection "debug"
[0m23:56:00.889630 [debug] [MainThread]: On debug: select 1 as id
[0m23:56:00.889630 [debug] [MainThread]: Opening a new connection, currently in state init
[0m23:56:01.709608 [debug] [MainThread]: SQL status: SUCCESS 1 in 0.823 seconds
[0m23:56:01.709608 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m23:56:01.725188 [info ] [MainThread]: [31m1 check failed:[0m
[0m23:56:01.725188 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml> not found

[0m23:56:01.734005 [debug] [MainThread]: Command `dbt debug` failed at 23:56:01.732906 after 7.20 seconds
[0m23:56:01.734776 [debug] [MainThread]: Connection 'debug' was left open.
[0m23:56:01.736629 [debug] [MainThread]: On debug: Close
[0m23:56:01.879560 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CA3ED4A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CAA3F3CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027CB9C2A8D0>]}
[0m23:56:01.879560 [debug] [MainThread]: Flushing usage events
[0m23:56:02.319082 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:00:40.625969 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015704316D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000157040BA5D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000157043161D0>]}


============================== 00:00:40.630855 | 9f553a80-dbb6-44c9-a915-74448c5390d6 ==============================
[0m00:00:40.630855 [info ] [MainThread]: Running with dbt=1.9.1
[0m00:00:40.631986 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:00:40.653876 [info ] [MainThread]: dbt version: 1.9.1
[0m00:00:40.654917 [info ] [MainThread]: python version: 3.11.5
[0m00:00:40.654917 [info ] [MainThread]: python path: C:\Users\lina_\Desktop\wh_examarb\.venv\Scripts\python.exe
[0m00:00:40.656224 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m00:00:41.547025 [info ] [MainThread]: Using profiles dir at C:\Users\lina_\.dbt
[0m00:00:41.547999 [info ] [MainThread]: Using profiles.yml file at C:\Users\lina_\.dbt\profiles.yml
[0m00:00:41.547999 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
[0m00:00:41.549151 [info ] [MainThread]: adapter type: snowflake
[0m00:00:41.550620 [info ] [MainThread]: adapter version: 1.9.0
[0m00:00:41.551162 [info ] [MainThread]: Configuration:
[0m00:00:41.552169 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m00:00:41.553249 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m00:00:41.553389 [info ] [MainThread]: Required dependencies:
[0m00:00:41.554926 [debug] [MainThread]: Executing "git --help"
[0m00:00:41.585178 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m00:00:41.585178 [debug] [MainThread]: STDERR: "b''"
[0m00:00:41.586337 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m00:00:41.587402 [info ] [MainThread]: Connection:
[0m00:00:41.588409 [info ] [MainThread]:   account: ew35625.west-europe.azure
[0m00:00:41.588993 [info ] [MainThread]:   user: dbt_transformer
[0m00:00:41.589604 [info ] [MainThread]:   database: wh_db
[0m00:00:41.590652 [info ] [MainThread]:   warehouse: compute_wh
[0m00:00:41.591891 [info ] [MainThread]:   role: dbt_role
[0m00:00:41.592397 [info ] [MainThread]:   schema: warehouse
[0m00:00:41.593424 [info ] [MainThread]:   authenticator: None
[0m00:00:41.594431 [info ] [MainThread]:   oauth_client_id: None
[0m00:00:41.594431 [info ] [MainThread]:   query_tag: None
[0m00:00:41.596436 [info ] [MainThread]:   client_session_keep_alive: False
[0m00:00:41.597436 [info ] [MainThread]:   host: None
[0m00:00:41.599635 [info ] [MainThread]:   port: None
[0m00:00:41.600645 [info ] [MainThread]:   proxy_host: None
[0m00:00:41.601650 [info ] [MainThread]:   proxy_port: None
[0m00:00:41.603659 [info ] [MainThread]:   protocol: None
[0m00:00:41.604862 [info ] [MainThread]:   connect_retries: 1
[0m00:00:41.606111 [info ] [MainThread]:   connect_timeout: None
[0m00:00:41.607063 [info ] [MainThread]:   retry_on_database_errors: False
[0m00:00:41.608237 [info ] [MainThread]:   retry_all: False
[0m00:00:41.608237 [info ] [MainThread]:   insecure_mode: False
[0m00:00:41.609717 [info ] [MainThread]:   reuse_connections: True
[0m00:00:41.611146 [info ] [MainThread]: Registered adapter: snowflake=1.9.0
[0m00:00:41.988300 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m00:00:42.063255 [debug] [MainThread]: Using snowflake connection "debug"
[0m00:00:42.063255 [debug] [MainThread]: On debug: select 1 as id
[0m00:00:42.064255 [debug] [MainThread]: Opening a new connection, currently in state init
[0m00:00:42.902663 [debug] [MainThread]: SQL status: SUCCESS 1 in 0.839 seconds
[0m00:00:42.907037 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m00:00:42.909040 [info ] [MainThread]: [31m1 check failed:[0m
[0m00:00:42.910358 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml> not found

[0m00:00:42.913499 [debug] [MainThread]: Command `dbt debug` failed at 00:00:42.913499 after 2.38 seconds
[0m00:00:42.913499 [debug] [MainThread]: Connection 'debug' was left open.
[0m00:00:42.913499 [debug] [MainThread]: On debug: Close
[0m00:00:43.065236 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001577DA84A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015704316510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015704317A10>]}
[0m00:00:43.068274 [debug] [MainThread]: Flushing usage events
[0m00:00:43.551424 [debug] [MainThread]: An error was encountered while trying to flush usage events
